function Hd = MyFirFilter(x,fs,)
%LOWPASSM Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.14 and Signal Processing Toolbox 9.2.
% Generated on: 08-Mar-2025 11:54:38

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 25000;  % Sampling Frequency

Fpass = 6250;            % Passband Frequency
Fstop = 12500;           % Stopband Frequency
% Dpass = 0.057501127785;  % Passband Ripple
% Dstop = 0.0001;          % Stopband Attenuation
% dens  = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
